# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-14 21:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('year', models.CharField(blank=True, max_length=9)),
                ('eleves', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('prof', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='prof', to=settings.AUTH_USER_MODEL)),
                ('professeurs', models.ManyToManyField(default=1, related_name='professeurs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Colle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('author', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('object_id', models.PositiveIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('level', models.CharField(blank=True, max_length=50)),
                ('difficulty', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('popularity', models.DecimalField(decimal_places=1, default=5, max_digits=2)),
                ('quality', models.DecimalField(decimal_places=1, default=5, max_digits=2)),
                ('enonce_latex', models.TextField(blank=True)),
                ('enonce_html', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('indication_latex', models.TextField(blank=True)),
                ('indication_html', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('figure', models.TextField(blank=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('visibility', models.CharField(choices=[('A', 'Public'), ('P', 'Personnalisé')], default='A', max_length=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MacroLatex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('macro', models.TextField(blank=True)),
                ('description', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Oral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveIntegerField()),
                ('commentaire', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exercices', models.ManyToManyField(to='exobase.Exercice')),
            ],
        ),
        migrations.CreateModel(
            name='OrderFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_to_folder', to='exobase.Exercice')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exobase.Folder')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('organization', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('work', models.CharField(choices=[('E', 'Etudiant'), ('P', 'Professeur'), ('A', 'Autre')], max_length=1)),
                ('website', models.URLField(blank=True, default='')),
                ('avatar', models.ImageField(blank=True, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.DecimalField(decimal_places=1, default=5, max_digits=2)),
                ('enonce_latex', models.TextField(blank=True)),
                ('enonce_html', models.TextField(blank=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('visibility', models.CharField(choices=[('A', 'Public'), ('P', 'Personnalisé')], default='A', max_length=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exobase.Exercice')),
                ('macro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exobase.MacroLatex')),
            ],
        ),
        migrations.AddField(
            model_name='folder',
            name='exercices',
            field=models.ManyToManyField(related_name='in_folder', through='exobase.OrderFolder', to='exobase.Exercice'),
        ),
        migrations.AddField(
            model_name='exercice',
            name='macro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exobase.MacroLatex'),
        ),
        migrations.AddField(
            model_name='exercice',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='collection',
            name='folders',
            field=models.ManyToManyField(to='exobase.Folder'),
        ),
        migrations.AddField(
            model_name='colle',
            name='oraux',
            field=models.ManyToManyField(to='exobase.Oral'),
        ),
    ]
