# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 16:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exobase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('author', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('object_id', models.PositiveIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='MacroLatex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('macro', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveIntegerField()),
                ('commentaire', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('organization', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('work', models.CharField(choices=[('E', 'Etudiant'), ('P', 'Professeur'), ('A', 'Autre')], max_length=1)),
                ('website', models.URLField(blank=True, default='')),
                ('avatar', models.ImageField(upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.DecimalField(decimal_places=1, default=5, max_digits=2)),
                ('enonce_latex', models.TextField(blank=True)),
                ('enonce_html', models.TextField(blank=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='exercice',
            name='corrige_text',
        ),
        migrations.RemoveField(
            model_name='exercice',
            name='enonce_text',
        ),
        migrations.AddField(
            model_name='exercice',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exercice',
            name='difficulty',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='exercice',
            name='enonce_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exercice',
            name='enonce_latex',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exercice',
            name='figure',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exercice',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='exercice',
            name='indication_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exercice',
            name='indication_latex',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exercice',
            name='level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='exercice',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='exercice',
            name='popularity',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=2),
        ),
        migrations.AddField(
            model_name='exercice',
            name='quality',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=2),
        ),
        migrations.AddField(
            model_name='exercice',
            name='visibility',
            field=models.CharField(choices=[('A', 'Public'), ('P', 'Personnalisé')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='folder',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='orderfolder',
            name='exercice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_to_folder', to='exobase.Exercice'),
        ),
        migrations.AddField(
            model_name='solution',
            name='exercice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exobase.Exercice'),
        ),
        migrations.AddField(
            model_name='solution',
            name='macro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exobase.MacroLatex'),
        ),
        migrations.AddField(
            model_name='oral',
            name='exercices',
            field=models.ManyToManyField(to='exobase.Exercice'),
        ),
        migrations.AddField(
            model_name='collection',
            name='folders',
            field=models.ManyToManyField(to='exobase.Folder'),
        ),
        migrations.AddField(
            model_name='colle',
            name='oraux',
            field=models.ManyToManyField(to='exobase.Oral'),
        ),
        migrations.AddField(
            model_name='exercice',
            name='macro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exobase.MacroLatex'),
        ),
    ]
