# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 07:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exobase', '0003_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='prof',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='prof', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
