# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exobase', '0004_auto_20170906_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='visibility',
            field=models.CharField(choices=[('A', 'Public'), ('P', 'Personnalisé')], default='A', max_length=1),
        ),
    ]
