# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 13:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exobase', '0006_folder_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='classe',
            name='professeurs',
            field=models.ManyToManyField(default=1, related_name='professeurs', to=settings.AUTH_USER_MODEL),
        ),
    ]
