# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exobase', '0007_auto_20170910_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='macrolatex',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
